export enum SettingValueType {
    STRING = "String",
    BOOLEAN = "Boolean",
    NUMBER = "Number",
}

export enum PeriodOfTime {
    MORNING = "Morning",
    AFTERNOON = "Afternoon",
}

export enum FullPeriodOfTime {
    MORNING = "Morning",
    AFTERNOON = "Afternoon",
    ALL = "All",
}

export enum SettingKey {
    MORNING_WORK_FROM = "MORNING_WORK_FROM",
    MORNING_WORK_TO = "MORNING_WORK_TO",

    AFTERNOON_WORK_FROM = "AFTERNOON_WORK_FROM",
    AFTERNOON_WORK_TO = "AFTERNOON_WORK_TO",
    ATTENDANCE_REGISTER_DELAY_ALLOW = "ATTENDANCE_REGISTER_DELAY_ALLOW",
    ATTENDANCE_PRIVATE_KEY = "ATTENDANCE_PRIVATE_KEY",

    WORKSPACE_BSSID = "WORKSPACE_BSSID",
    WORKSPACE_IP_ADDRESS = "WORKSPACE_IP_ADDRESS",

    FULL_TIME_REGISTER_LATE_PER_MONTH = "FULL_TIME_REGISTER_LATE_PER_MONTH",
    FULL_TIME_REGISTER_ABSENT_PER_MONTH = "FULL_TIME_REGISTER_ABSENT_PER_MONTH",
    FULL_TIME_REQUIRED_WORK_DAY_PER_MONTH = "FULL_TIME_REQUIRED_WORK_DAY_PER_MONTH",
    PART_TIME_REGISTER_LATE_PER_MONTH = "PART_TIME_REGISTER_LATE_PER_MONTH",
    PART_TIME_REGISTER_ABSENT_PER_MONTH = "PART_TIME_REGISTER_ABSENT_PER_MONTH",
    PART_TIME_REQUIRED_WORK_DAY_PER_MONTH = "PART_TIME_REQUIRED_WORK_DAY_PER_MONTH",

    TEAM_LIST = "TEAM_LIST",
}